name: Backend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package*.json'
      - 'tsconfig*.json'
      - 'Dockerfile'
      - '.github/workflows/backend-ci.yml'

jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: false

      - name: Check formatting with Prettier
        run: npm run format:check
        continue-on-error: false

      - name: Build TypeScript
        run: npm run build
        continue-on-error: false

  validate-docker:
    name: Validate Dockerfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: payment-centralizer:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [lint-and-build, validate-docker]
    if: always()

    steps:
      - name: Check CI Results
        run: |
          if [[ "${{ needs.lint-and-build.result }}" == "failure" ]] || [[ "${{ needs.validate-docker.result }}" == "failure" ]]; then
            echo "❌ CI checks failed"
            exit 1
          else
            echo "✅ All CI checks passed"
          fi
